name:     cpp-parser
version:  0.1.0.0

dependencies:
- base >= 4.7 && < 5
- parsec

executables:
  cpp-parser-exe:
    main:         Main.hs
    source-dirs:  app
    ghc-options:
    - -O0
    dependencies:
    - cpp-parser

library:
  source-dirs:    src

tests:
  cpp-parser-test:
    main:         Spec.hs
    source-dirs:  test
    ghc-options:
    - -O0
    dependencies:
    - hspec
    - cpp-parser
